<!DOCTYPE html>
<html lang="cs-cz">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
	<title><?= $title ?></title>
	<meta name="description" content="<?= $description ?>" />
	<meta name="keywords" content="<?= $keywords ?>" />
	<link rel="stylesheet" href="../../www/css/style.css" type="text/css"/>
</head>

<body>
<article>
	<?php $this->controller->renderView(); ?>
</article>
</body>
</html>