<!DOCTYPE html>
<html lang="cs-cz">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
<!--	<title>--><?php //= $title ?><!--</title>-->
<!--	<meta name="description" content="--><?php //= $description ?><!--" />-->
<!--	<meta name="keywords" content="--><?php //= $keywords ?><!--" />-->
	<link rel="stylesheet" href="../../www/css/style.css" type="text/css"/>
</head>

<body>
<article>
	<?php $this->controller->renderView(); ?>
</article>
</body>
</html>